// Danh mục gợi ý cho form học sinh (ô "Trường học" và "Khối thi/kỳ thi").
// Các ô này là ô nhập có gợi ý (<datalist>): vẫn cho gõ tự do, nên giá trị cũ
// trong CSDL (vd "A00", tên trường chưa có trong danh sách) không bị mất.
// Cột CSDL giữ nguyên tên `truong_thpt` / `khoi_thi` (không cần migration).

export const KY_THI_OPTIONS: string[] = [
  "Đánh giá năng lực TP.HCM (V-ACT)",
  "SAT",
  "Nội trú hệ Nội-Nhi | UMP",
  "Nội trú hệ Ngoại-Sản | UMP",
  "Thạc sĩ UMP",
];

export const KHOI_THI_PLACEHOLDER = "khối A01, V-ACT, Nội trú Nội - Nhi,...";

// Trường đại học đào tạo Y – Dược. Nguồn đối chiếu: Medibase (2026) và
// Thư viện pháp luật (2026) + kiến thức bổ sung; cần rà lại khi có thay đổi.
export const TRUONG_DAI_HOC_Y_DUOC_CONG_LAP: string[] = [
  "Trường Đại học Y Hà Nội (HMU)",
  "Trường Đại học Dược Hà Nội (HUP)",
  "Trường Đại học Y Dược – Đại học Quốc gia Hà Nội",
  "Học viện Quân y",
  "Học viện Y Dược học cổ truyền Việt Nam",
  "Trường Đại học Y tế Công cộng",
  "Trường Đại học Kỹ thuật Y tế Hải Dương",
  "Trường Đại học Y Dược Hải Phòng",
  "Trường Đại học Y Dược Thái Bình",
  "Trường Đại học Điều dưỡng Nam Định",
  "Trường Đại học Y Dược – Đại học Thái Nguyên",
  "Trường Đại học Y khoa Vinh",
  "Trường Đại học Y Dược – Đại học Huế",
  "Trường Y Dược – Đại học Đà Nẵng",
  "Trường Đại học Kỹ thuật Y – Dược Đà Nẵng",
  "Trường Đại học Tây Nguyên (Khoa Y Dược)",
  "Trường Đại học Y Dược TP.HCM (UMP)",
  "Trường Đại học Y khoa Phạm Ngọc Thạch (PNTU)",
  "Trường Đại học Khoa học Sức khỏe – ĐHQG-HCM",
  "Trường Đại học Y Dược Cần Thơ",
  "Trường Y Dược – Đại học Trà Vinh",
];

export const TRUONG_DAI_HOC_Y_DUOC_TU_THUC: string[] = [
  "Trường Đại học VinUni",
  "Trường Đại học Phenikaa",
  "Trường Đại học Đại Nam",
  "Trường Đại học Kinh doanh và Công nghệ Hà Nội",
  "Trường Đại học Y khoa Tokyo Việt Nam",
  "Trường Đại học Duy Tân",
  "Trường Đại học Đông Á",
  "Trường Đại học Phan Châu Trinh",
  "Trường Đại học Y Dược Buôn Ma Thuột",
  "Trường Đại học Yersin Đà Lạt",
  "Trường Đại học Nguyễn Tất Thành",
  "Trường Đại học Quốc tế Hồng Bàng",
  "Trường Đại học Văn Lang",
  "Trường Đại học Công nghệ TP.HCM (HUTECH)",
  "Trường Đại học Tân Tạo",
  "Trường Đại học Nam Cần Thơ",
  "Trường Đại học Võ Trường Toản",
];

// Trường THPT/phổ thông theo tỉnh/thành (34 tỉnh, thành sau sắp xếp 2025).
// Nguồn: Wikipedia tiếng Việt "Danh sách trường trung học phổ thông tại Việt Nam"
// + các trang danh sách theo tỉnh, trang trường chuyên (thu thập 10/2026).
// ⚠️ KHÔNG PHẢI DANH SÁCH CHÍNH THỨC/ĐẦY ĐỦ: Wikipedia chỉ có danh sách chi tiết
// cho một số tỉnh/thành; các tỉnh còn lại mới có trường chuyên/nổi tiếng.
// Ô nhập vẫn cho gõ tự do. Nên thay bằng danh mục của Bộ/Sở GD&ĐT khi có file.
const THPT_THEO_TINH: Record<string, string[]> = {
  "TP.HCM": [
    "Phổ thông Năng Khiếu, Đại học Quốc gia TP.HCM",
    "THPT chuyên Trần Đại Nghĩa",
    "THPT chuyên Lê Hồng Phong",
    "THPT chuyên Lê Quý Đôn",
    "THPT chuyên Hùng Vương",
    "THPT Năng khiếu Thể dục Thể thao TP.HCM",
    "THPT Năng khiếu Thể dục Thể thao Nguyễn Thị Định",
    "Phổ thông Năng khiếu Thể thao Olympic – Đại học Thể dục Thể thao TPHCM",
    "THPT Năng khiếu Thể dục Thể thao Bình Chánh",
    "THPT Bùi Thị Xuân",
    "THPT Trưng Vương",
    "THPT Ernst Thälmann",
    "THPT Lương Thế Vinh",
    "THCS - THPT Trần Đại Nghĩa",
    "THPT Lê Quý Đôn",
    "THPT Nguyễn Thị Minh Khai",
    "THPT Marie Curie",
    "THPT Nguyễn Thị Diệu",
    "THPT Lê Thị Hồng Gấm",
    "THPT Nguyễn Trãi",
    "THPT Nguyễn Hữu Thọ",
    "THPT Hùng Vương",
    "Trung học Thực hành Sài Gòn",
    "Trung học Thực hành - Đại học Sư phạm TP.HCM",
    "THPT Trần Khai Nguyên",
    "THPT Trần Hữu Trang",
    "THPT Bình Phú",
    "THPT Nguyễn Tất Thành",
    "THPT Phạm Phú Thứ",
    "THPT Mạc Đĩnh Chi",
    "THPT Ngô Quyền",
    "THPT Lê Thánh Tôn",
    "Tiểu học - THCS - THPT Nam Sài Gòn",
    "THPT Tân Phong",
    "THPT Lương Văn Can",
    "THPT Ngô Gia Tự",
    "THPT Tạ Quang Bửu",
    "THPT Nguyễn Văn Linh",
    "THPT Võ Văn Kiệt",
    "THPT Nguyễn An Ninh",
    "THCS - THPT Sương Nguyệt Anh",
    "THPT Nguyễn Du",
    "THPT Nguyễn Khuyến",
    "THCS - THPT Diên Hồng",
    "THPT Nam Kỳ Khởi Nghĩa",
    "THPT Nguyễn Hiền",
    "THPT Trần Quang Khải",
    "THPT Võ Trường Toản",
    "THPT Trường Chinh",
    "THPT Thạnh Lộc",
    "TH - THCS và THPT Lê Thị Riêng",
    "THPT Phan Văn Hớn",
    "THPT An Lạc",
    "THPT Nguyễn Hữu Cảnh",
    "THPT Bình Tân",
    "THPT Bình Hưng Hòa",
    "THPT Vĩnh Lộc",
    "THPT Hoàng Thế Thiện",
    "THPT Võ Thị Sáu",
    "THPT Phan Đăng Lưu",
    "THPT Hoàng Hoa Thám",
    "THPT Thanh Đa",
    "THPT Trần Văn Giàu",
    "THPT Gia Định",
    "THPT Nguyễn Trung Trực",
    "THPT Gò Vấp",
    "THPT Nguyễn Công Trứ",
    "THPT Trần Hưng Đạo",
    "THPT Phú Nhuận",
    "THPT Hàn Thuyên",
    "THPT Nguyễn Thượng Hiền",
    "THPT Nguyễn Thái Bình",
    "THPT Nguyễn Chí Thanh",
    "THPT Trần Phú",
    "THPT Tân Bình",
    "THPT Tây Thạnh",
    "THPT Lê Trọng Tấn",
    "THPT Thoại Ngọc Hầu",
    "THPT Nguyễn Hữu Huân",
    "THPT Thủ Đức",
    "THPT Thủ Thiêm",
    "THPT Giồng Ông Tố",
    "THPT Nguyễn Huệ",
    "THPT Tam Phú",
    "THPT Phước Long",
    "THPT Long Trường",
    "THPT Hiệp Bình",
    "THPT Đào Sơn Tây",
    "THPT Nguyễn Văn Tăng",
    "THPT Linh Trung",
    "THPT Bình Chiểu",
    "THPT Dương Văn Thì",
    "THPT Bình Chánh",
    "THPT Lê Minh Xuân",
    "THPT Đa Phước",
    "THPT Tân Túc",
    "THPT Vĩnh Lộc B",
    "THPT Phong Phú",
    "THPT Bình Khánh",
    "THPT Cần Thạnh",
    "THPT An Nghĩa",
    "THCS - THPT Thạnh An",
    "THPT Củ Chi",
    "THPT Trung Phú",
    "THPT An Nhơn Tây",
    "THPT Quang Trung",
    "THPT Trung Lập",
    "THPT Phú Hòa",
    "THPT Tân Thông Hội",
    "THPT Lý Thường Kiệt",
    "THPT Nguyễn Hữu Cầu",
    "THPT Bà Điểm",
    "THPT Nguyễn Hữu Tiến",
    "THPT Nguyễn Văn Cừ",
    "THPT Phạm Văn Sáng",
    "THPT Hồ Thị Bi",
    "THPT Long Thới",
    "THPT Phước Kiển",
    "THPT Dương Văn Dương",
    "Quốc tế Việt Nam - Phần Lan",
    "THPT Quốc tế Việt Úc",
    "Tiểu học, THCS và THPT Hermann Gmeiner",
    "THCS - THPT Đinh Thiện Lý",
    "Tiểu học - THCS và THPT Quốc tế Thành phố Hồ Chí Minh",
    "Tiểu học - THCS và THPT Quốc tế Thành phố Hồ Chí Minh - Học viện Mỹ",
    "Tiểu học - THCS - THPT Việt Úc",
    "Tiểu học - THCS - THPT Việt Mỹ",
    "THPT Việt Mỹ Anh",
    "Tiểu học, THCS, THPT Quốc Tế Khai Sáng (Renaissance)",
    "Quốc tế Dạy bằng Tiếng Anh - BIS",
    "Tiểu học - THCS - THPT Quốc tế Anh - Thành phố Hồ Chí Minh",
    "Tiểu học - THCS và THPT Quốc tế Nam Sài Gòn",
    "Quốc tế Châu Âu TP. Hồ Chí Minh",
    "Quốc tế Đức TP.Hồ Chí Minh",
    "Tiểu học, THCS, THPT Quốc Tế Sài Gòn Pearl",
    "Tiểu học, THCS, THPT Quốc tế Anglophone",
    "Tiểu học - THCS - THPT Hàn Quốc Toàn Cầu",
    "Quốc tế TAS - The American School HCMC",
    "Tiểu học, THCS và THPT Emasi Vạn Phúc - Emasi Nam Long",
    "Phổ thông Song ngữ Quốc tế Wellspring Saigon - Trường Tiểu học - THCS - THPT Mùa Xuân",
    "Tiểu học - THCS - THPT Quốc tế Á Châu",
    "Tiểu học - THCS - THPT Quốc tế Nam Mỹ",
    "Tiểu học - THCS - THPT quốc tế Nam Úc",
    "Tiểu học - THCS - THPT Tây Úc",
    "Quốc tế Willam Penn (Penn School)",
    "Tiểu học, THCS - THPT Quốc Tế",
    "Tiểu học - THCS - THPT Vinschool",
    "Tiểu học - THCS - THPT Anh Quốc",
    "THCS và THPT Quốc tế APU",
    "Tiểu học - THCS và THPT Albert Einstein",
    "Tiểu học - THCS - THPT quốc tế Bắc Mỹ",
    "Tiểu học - THCS - THPT Sao Việt",
    "Tiểu học, THCS và THPT Quốc tế Canada",
    "Tiểu học, THCS và THPT Quốc tế Singapore",
    "Tiểu học - THCS - THPT Khai Nguyên",
    "Tiểu học - THCS - THPT Tesla",
    "Tiểu học - THCS - THPT Tuệ Đức",
    "Tiểu học - THCS - THPT Hoàng Gia",
    "Tiểu học - THCS - THPT Quốc tế Pháp - Marguerite Duras",
    "Tiểu học - THCS - THPT Khải Hoàn (Nam Sài Gòn)",
    "Tiểu học - THCS - THPT Kiến Tạo (Me Since 1988)",
    "THCS - THPT Tre Việt",
    "THCS - THPT Đăng Khoa",
    "THCS - THPT Nguyễn Bỉnh Khiêm",
    "THPT An Đông",
    "THPT Thăng Long",
    "THPT Khai Trí",
    "THCS - THPT Văn Lang",
    "THCS - THPT Quang Trung - Nguyễn Huệ",
    "THCS – THPT Phan Bội Châu",
    "THPT Quốc Trí",
    "THCS - THPT Đức Trí",
    "Tiểu học, THCS, THPT Trí Việt",
    "THCS - THPT Duy Tân",
    "Tiểu học - THCS - THPT Vạn Hạnh",
    "Tiểu học - THCS - THPT Trương Vĩnh Ký",
    "THPT Trần Quốc Tuấn",
    "THCS - THPT Bắc Sơn",
    "THCS - THPT Đông Du",
    "THCS - THPT Phùng Hưng",
    "THCS - THPT Lạc Hồng",
    "THPT Việt Âu",
    "THCS - THPT Ngọc Viễn Đông",
    "THCS - THPT Hoa Lư",
    "THCS - THPT Hàn Việt",
    "THPT Đông Dương",
    "Tiểu học - THCS - THPT Mỹ Việt",
    "THCS - THPT Lê Khiết",
    "THCS - THPT Khai Minh",
    "THPT Đông Đô",
    "THPT Phan Hữu Ích",
    "THPT Sài Gòn",
    "Tiểu học - THCS - THPT Lam Sơn",
    "THCS - THPT Hồng Hà",
    "THCS - THPT Phạm Ngũ Lão",
    "Tiểu học - THCS - THPT Sài Gòn - Gia Định",
    "THCS - THPT Nguyễn Tri Phương",
    "THPT Việt Nhật",
    "THPT Lý Thái Tổ",
    "THCS - THPT Âu Lạc",
    "Tiểu học - THCS - THPT Đại Việt",
    "THCS - THPT Văn Hóa Việt",
    "THPT Hưng Đạo",
    "THCS - THPT Thái Bình",
    "Tiểu học - THCS - THPT Thanh Bình",
    "THCS - THPT Việt Thanh",
    "THCS - THPT Bắc Ái",
    "THCS - THPT Hai Bà Trưng",
    "Tiểu học - THCS - THPT Thái Bình Dương",
    "THPT Thủ Khoa Huân",
    "THCS - THPT Nhân Văn",
    "THCS - THPT Trí Đức",
    "THCS - THPT Đinh Tiên Hoàng",
    "THCS - THPT Đào Duy Anh",
    "THCS - THPT Hồng Đức",
    "Tiểu học - THCS - THPT Hòa Bình",
    "THCS - THPT Nam Việt",
    "THPT Vĩnh Viễn",
    "Tiểu học - THCS - THPT Lê Thánh Tông",
    "THCS - THPT Minh Đức",
    "THCS - THPT Trần Cao Vân",
    "Tiểu học - THCS - THPT Tân Phú",
    "TH - THCS - THPT Đông Á",
    "THPT An Dương Vương",
    "THPT Huỳnh Thúc Kháng",
    "THPT Thành Nhân",
    "THCS - THPT Ngôi Sao",
    "THCS - THPT Phan Châu Trinh",
    "THPT Phú Lâm",
    "THPT Trần Nhân Tông",
    "Tiểu học - THCS - THPT Chu Văn An",
    "Tiểu học - THCS - THPT Trí Tuệ Việt",
    "THPT Hàm Nghi",
    "THPT Phương Nam",
    "Tiểu học - THCS - THPT Ngô Thời Nhiệm",
    "THCS - THPT Hoa Sen",
    "THPT Bách Việt",
    "Mầm non - Tiểu học - THCS - THPT Quảng Ích",
    "THPT Chiến Thắng",
    "THPT Vũng Tàu",
    "THPT Nguyễn Khuyến - Bà Rịa - Vũng Tàu",
    "THPT Trần Nguyên Hãn",
    "THPT Nguyễn Huệ - Bà Rịa - Vũng Tàu",
    "THPT Đinh Tiên Hoàng",
    "THPT Nguyễn Bỉnh Khiêm",
    "THPT Bà Rịa",
    "THPT Châu Thành",
    "THPT Phú Mỹ",
    "THPT Hắc Dịch",
    "THPT Trần Văn Quan",
    "THPT Trần Quang Khải - Bà Rịa - Vũng Tàu",
    "THPT Long Hải - Phước Tỉnh",
    "THPT Minh Đạm",
    "THPT Võ Thị Sáu - Bà Rịa - Vũng Tàu",
    "THPT Dương Bạch Mai",
    "THPT Nguyễn Du - Bà Rịa - Vũng Tàu",
    "THPT Nguyễn Trãi - Bà Rịa - Vũng Tàu",
    "THPT Ngô Quyền - Bà Rịa - Vũng Tàu",
    "THPT Trần Phú - Bà Rịa - Vũng Tàu",
    "THPT Nguyễn Văn Cừ - Bà Rịa - Vũng Tàu",
    "THPT Phước Bửu",
    "THPT Xuyên Mộc",
    "THPT Hòa Hội",
    "THPT Bưng Riềng",
    "THPT Hòa Bình",
    "THPT Lê Hồng Phong - Vũng Tàu",
    "THCS - THPT Song Ngữ",
    "THPT Chu Văn An - Bà Rịa",
    "THPT Nguyễn Thị Minh Khai - Bà Rịa - Vũng Tàu",
    "THPT An Mỹ",
    "THPT Bàu Bàng",
    "THPT Bình An",
    "THPT Bình Phú - Bình Dương",
    "THPT Bến Cát",
    "THPT Dĩ An",
    "THPT Dầu Tiếng",
    "THPT Huỳnh Văn Nghệ",
    "THPT Lê Lợi",
    "THPT Long Hòa",
    "THPT Nguyễn An Ninh - Bình Dương",
    "THCS và THPT Nguyễn Huệ - Bình Dương",
    "THPT Nguyễn Trãi - Bình Dương",
    "THPT Nguyễn Đình Chiểu",
    "THPT Phước Hòa",
    "THPT Phước Vĩnh",
    "THPT Thái Hòa",
    "THPT Thường Tân",
    "THPT Trần Văn Ơn",
    "THPT Trịnh Hoài Đức",
    "THPT Tân Bình - Bình Dương",
    "THPT Tân Phước Khánh",
    "THPT Tây Nam",
    "THCS và THPT Tây Sơn",
    "THCS - THPT Minh Hòa",
    "THPT Võ Minh Đức",
    "THPT Nguyễn Thị Minh Khai - Bình Dương",
    "THPT phường Dĩ An",
    "THPT Lai Uyên",
    "THCS & THPT Nguyễn Khuyến",
    "TH,THCS & THPT Ngô Thời Nhiệm",
    "Trung - Tiểu học Pétrus-Ký",
    "TH, THCS & THPT Phan Châu Trinh",
    "TH,THCS & THPT Việt Anh",
    "TH, THCS & THPT Việt Anh 2",
    "TH - THCS & THPT Đức Trí",
    "THPT Hoàng Diệu",
    "Tiểu học - THCS - THPT Lương Thế Vinh",
    "Tiểu học - THCS và THPT B.School",
    "Tiểu học - THCS - THPT Marie Curie",
  ],
  "Hà Nội": [
    "THPT chuyên Hà Nội - Amsterdam",
    "THPT chuyên Nguyễn Huệ",
    "THPT chuyên Chu Văn An",
    "THPT chuyên Sơn Tây",
    "THPT chuyên Đại học Sư phạm Hà Nội",
    "THPT chuyên Ngoại ngữ",
    "THPT chuyên Khoa học Tự nhiên",
    "THPT chuyên Khoa học Xã hội và Nhân văn",
    "THPT Phan Đình Phùng",
    "THPT Đoàn Kết - Hai Bà Trưng",
    "THPT Thăng Long",
    "THPT Nguyễn Gia Thiều",
    "THPT Chương Mỹ A",
    "THPT Trần Phú - Hoàn Kiếm",
    "THPT Việt Đức",
    "THPT Trung Văn",
    "THPT Lê Quý Đôn - Đống Đa",
    "THPT Quang Trung - Đống Đa",
    "THPT Nguyễn Trãi - Ba Đình",
    "THPT Phạm Hồng Thái",
    "THPT Lê Lợi",
    "THPT Lê Quý Đôn - Hà Đông",
    "THPT Quang Trung - Hà Đông",
    "THPT Trần Nhân Tông",
    "THPT Việt Nam - Ba Lan",
    "THPT Hoàng Văn Thụ",
    "THPT Trương Định",
    "THPT Khương Đình",
    "TH, THCS và THPT Khương Hạ",
    "THPT Kim Liên",
    "THPT Thạch Bàn",
    "THPT Cầu Giấy",
    "THPT Đống Đa",
    "THPT Hoàng Cầu",
    "THPT Nguyễn Thị Minh Khai",
    "THPT Trần Hưng Đạo - Hà Đông",
    "THPT Tây Hồ",
    "THPT Phúc Lợi",
    "THPT Đại Mỗ",
    "THPT Trần Hưng Đạo - Thanh Xuân",
    "THPT Nhân Chính",
    "THPT Thượng Cát",
    "THPT Mỹ Đình",
    "THPT Tùng Thiện",
    "THPT Xuân Khanh",
    "THPT Lý Thường Kiệt",
    "THPT Xuân Đỉnh",
    "THPT Xuân Phương",
    "THPT Yên Hòa",
    "THPT Hoàng Quán Chi",
    "THPT Đỗ Mười",
    "THPT Hoài Đức B",
    "THPT Minh Quang",
    "THPT Bất Bạt",
    "THPT Nguyễn Văn Cừ",
    "THPT Tô Hiệu - Thường Tín",
    "THPT Tân Dân",
    "THPT Ngô Quyền - Ba Vì",
    "THPT Xuân Giang",
    "THPT Ngô Thì Nhậm",
    "THPT Phú Xuyên B",
    "THPT Nguyễn Du - Thanh Oai",
    "THPT Đan Phượng",
    "THPT Cổ Loa",
    "THPT Việt Hùng",
    "THPT Vạn Xuân - Hoài Đức",
    "THPT Cao Bá Quát - Gia Lâm",
    "THPT Dương Xá",
    "THPT Hai Bà Trưng - Thạch Thất",
    "THPT Ngọc Tảo",
    "THPT Chương Mỹ B",
    "THPT Lưu Hoàng",
    "THPT Hoài Đức A",
    "THPT Mỹ Đức B",
    "THPT Vân Tảo",
    "THPT Cao Bá Quát - Quốc Oai",
    "THPT Mỹ Đức C",
    "THPT Minh Khai",
    "THPT Minh Phú",
    "THPT Thọ Xuân",
    "THPT Tiền Phong",
    "TH, THCS và THPT Minh Châu",
    "THPT Hợp Thanh",
    "THPT Mỹ Đức A",
    "THPT Đông Mỹ",
    "THPT Nguyễn Quốc Trinh",
    "THPT Kim Anh",
    "THPT Hồng Thái",
    "THPT Tân Lập",
    "THPT Yên Viên",
    "THPT Phú Xuyên A",
    "THPT Phúc Thọ",
    "THPT Vân Cốc",
    "THPT Vân Nội",
    "THPT Phúc Thịnh",
    "THPT Đồng Quan",
    "THPT Chúc Động",
    "THPT Mê Linh",
    "THPT Quang Minh",
    "THPT Quảng Oai",
    "THPT Quốc Oai",
    "THPT Phan Huy Chú - Quốc Oai",
    "THPT Đa Phúc",
    "THPT Sóc Sơn",
    "THPT Hoài Đức C",
    "THPT Ba Vì",
    "Phổ thông Dân tộc Nội trú",
    "THPT Thanh Oai B",
    "THPT Phùng Khắc Khoan - Thạch Thất",
    "THPT Minh Hà",
    "THPT Thạch Thất",
    "THPT Thanh Oai A",
    "THPT Ngọc Hồi",
    "THPT Bắc Thăng Long",
    "THPT Đông Anh",
    "THPT Liên Hà",
    "THPT Lý Tử Tấn",
    "THPT Nguyễn Trãi - Thường Tín",
    "THPT Thường Tín",
    "THPT Tự Lập",
    "THPT Nguyễn Văn Trỗi",
    "THPT Trung Giã",
    "THPT Đại Cường",
    "THPT Ứng Hòa B",
    "THPT Trần Đăng Ninh",
    "THPT Ứng Hòa A",
    "THPT Xuân Mai",
    "THPT Tiến Thịnh",
    "THPT Yên Lãng",
    "THPT Bắc Lương Sơn",
    "THCS - THPT Trần Quốc Tuấn",
    "THPT Phan Huy Chú - Đống Đa",
    "THCS - THPT Nguyễn Tất Thành",
    "TH - THCS - THPT Thực nghiệm Khoa học Giáo dục",
    "THPT Khoa học Giáo dục",
    "THPT Lâm nghiệp",
    "Phổ thông Năng khiếu Thể dục Thể thao Hà Nội",
    "THPT Lương Thế Vinh",
    "THPT Lê Quý Đôn",
    "THPT Xuân Thủy",
    "THPT Đào Duy Từ",
    "THPT Huỳnh Thúc Kháng",
    "THPT Xa La",
    "THPT Phan Chu Trinh",
    "THPT Việt Hoàng",
    "THPT Vạn Xuân - Long Biên",
    "THPT Văn Lang",
    "THPT Văn Hiến",
    "THPT Trí Đức",
    "THPT Phan Bội Châu",
    "THPT Trần Thánh Tông",
    "THPT Trần Quang Khải",
    "THPT Trần Phú - Ba Vì",
    "THPT Trần Đại Nghĩa",
    "THPT Tô Hiệu - Gia Lâm",
    "THPT Tô Hiến Thành",
    "THPT Thanh Xuân",
    "THPT Tây Sơn",
    "THPT Tây Đô",
    "THPT Phương Nam",
    "THPT Phùng Khắc Khoan - Đống Đa",
    "THPT Phạm Văn Đồng",
    "THPT Nguyễn Văn Huyên",
    "THPT Nguyễn Tất Thành - Sơn Tây",
    "THPT Nguyễn Du - Mê Linh",
    "THPT Nguyễn Đình Chiểu",
    "THPT Ngô Tất Tố",
    "THPT Ngô Sĩ Liên",
    "THPT Ngô Quyền - Đông Anh",
    "THPT Ngô Gia Tự",
    "THPT Minh Trí",
    "THPT Mai Hắc Đế",
    "THPT Mạc Đĩnh Chi",
    "THPT Lý Thánh Tông",
    "THPT Lý Thái Tổ",
    "THPT Lương Văn Can",
    "THPT Lương Thế Vinh - Ba Vì",
    "THPT Lê Văn Thiêm",
    "THPT Lê Thánh Tông",
    "THPT Lê Ngọc Hân",
    "THPT Lam Hồng",
    "THPT Lạc Long Quân",
    "THPT Kinh Đô",
    "Phổ thông nội trú IVS",
    "THPT Hồng Hà",
    "THPT Hồng Đức",
    "THPT Hồng Bàng",
    "THPT Hoàng Mai",
    "THPT Hoàng Long",
    "THPT Hoàng Diệu",
    "THPT Hồ Xuân Hương",
    "THPT Hồ Tùng Mậu",
    "THPT Hermann Gmeiner Hà Nội",
    "THPT Hà Đông",
    "THPT Einstein",
    "THPT Đông Kinh",
    "THPT Đông Đô",
    "THPT Đinh Tiên Hoàng - Ba Đình",
    "THPT Đặng Tiến Đông",
    "THPT Đặng Thai Mai",
    "THPT Đại Việt",
    "THPT Bình Minh",
    "THPT Bắc Đuống",
    "THPT An Dương Vương",
    "THPT Hà Thành",
    "THPT Tạ Quang Bửu",
    "THPT M.V.Lômônôxốp",
    "THPT Phùng Hưng",
    "THPT Nguyễn Trực",
    "THPT Nguyễn Trường Tộ",
    "THPT Bắc Hà - Đống Đa",
    "THPT Ngô Gia Tự - Hà Đông",
    "THPT Nguyễn Bỉnh Khiêm - Phú Xuyên",
    "THPT Nguyễn Thượng Hiền - Ứng Hòa",
    "THPT Lương Văn Can - Cầu Giấy",
    "THPT Marie Curie",
    "THPT Nguyễn Bỉnh Khiêm",
    "Phổ thông FPT",
    "Phổ thông TH School",
    "THPT Ban Mai",
    "THPT Nguyễn Huệ",
    "THPT Phạm Ngũ Lão",
    "THPT Phan Huy Chú - Thạch Thất",
    "Phổ thông liên cấp Vinschool",
    "TH - THCS - THPT Archimedes Đông Anh",
    "THPT IVS",
    "THPT Global",
    "Phổ thông Liên cấp SenTia",
    "THPT Quốc tế Thăng Long",
    "Phổ thông Liên cấp Hòa Bình Latrobe - Hà Nội",
    "Phổ thông Liên cấp Hà Nội Adelaide School",
    "Phổ thông Dewey",
    "THPT Green City Academy",
    "Phổ thông Song ngữ Liên cấp Wellspring",
    "Phổ thông Liên cấp Olympia",
    "Phổ thông Liên cấp Newton",
    "Song ngữ Quốc tế Hà Nội Academy",
    "THPT Đoàn Thị Điểm",
    "Phổ thông Liên cấp Alfred Nobel",
    "Phổ thông Liên cấp Việt - Úc",
    "Phổ thông liên cấp TH School Hòa Lạc",
    "Phổ thông Quốc tế Việt Nam",
    "Phổ thông Liên cấp Vinschool The Harmony",
    "Phổ thông đa cấp Concordia Hanoi",
    "Phổ thông Song ngữ Quốc tế Horizon",
    "Phổ thông Quốc tế Singapore",
    "Phổ thông Quốc tế St.Paul",
    "Quốc tế Đa cấp Anh Việt Hoàng gia",
    "Quốc tế Hàn Quốc tại Hà Nội",
    "Quốc tế Nhật Bản",
    "Quốc tế Pháp Alexandre Yersin",
    "Phổ thông Quốc tế Hà Nội",
    "Quốc tế Liên Hợp Quốc Hà Nội",
    "Phổ thông võ thuật Bảo Long",
    "Phổ thông quốc tế ParkCity Hà Nội",
    "Phổ thông liên cấp Đa Trí Tuệ",
    "Phổ thông liên cấp Nguyễn Siêu",
    "Quốc Tế Anh BIS Hà Nội",
  ],
  "Vĩnh Long": [
    "THPT Chuyên Bến Tre",
    "THPT Lạc Long Quân",
    "THPT Nguyễn Đình Chiểu",
    "THPT Võ Trường Toản",
    "THPT Phan Liêm",
    "THPT Phan Ngọc Tòng",
    "THPT Phan Thanh Giản",
    "THPT Sương Nguyệt Anh",
    "THPT Tán Kế",
    "THPT Huỳnh Tấn Phát",
    "THPT Lê Hoàng Chiếu",
    "THPT Lê Quí Đôn",
    "THPT Thạnh Phước",
    "THPT Diệp Minh Châu",
    "THPT Mạc Đĩnh Chi",
    "THPT Nguyễn Huệ",
    "THPT Trần Văn Ơn",
    "THPT Trần Văn Kiết",
    "THPT Trương Vĩnh Ký",
    "THPT Chợ Lách",
    "THPT Nguyễn Ngọc Thăng",
    "THPT Nguyễn Thị Định",
    "THPT Nguyễn Trãi",
    "THPT Phan Văn Trị",
    "THPT Lê Anh Xuân",
    "THPT Ngô Văn Cấn",
    "THPT Nhuận Phú Tân",
    "THPT An Thới",
    "THPT Ca Văn Thỉnh",
    "THPT Chê-Ghêvara",
    "THPT Nguyễn Thị Minh Khai",
    "THPT Quản Trọng Hoàng",
    "THPT Đoàn Thị Điểm",
    "THPT Lê Hoài Đôn",
    "THPT Lương Thế Vinh",
    "THPT Trần Trường Sinh",
    "THPT chuyên Nguyễn Thiện Thành",
    "THPT chuyên Nguyễn Bỉnh Khiêm",
    "THPT Chê Ghê-va-ra",
    "Phổ thông Dân tộc nội trú THPT Trà Vinh",
    "THPT Phạm Thái Bường",
    "THPT Trà Vinh",
    "Thực hành Sư Phạm",
    "THCS và THPT Dân Thành",
    "THPT Duyên Hải",
    "THPT Long Hữu",
    "THPT Bùi Hữu Nghĩa",
    "THPT Dương Háo Học",
    "THPT Hồ Thị Nhâm",
    "THPT Nguyễn Đáng",
    "THPT Nguyễn Văn Hai",
    "THPT Cầu Kè",
    "THPT Phong Phú",
    "THPT Tam Ngãi",
    "THPT Cầu Ngang A",
    "THPT Cầu Ngang B",
    "THPT Dương Quang Đông",
    "THPT Nhị Trường",
    "THPT Hòa Lợi",
    "THPT Hòa Minh",
    "THCS và THPT Lương Hòa A",
    "THPT Vũ Đình Liệu",
    "THPT Đôn Châu",
    "THPT Long Khánh",
    "THPT Sơn Cang",
    "Phổ thông Dân tộc nội trú THCS và THPT Tiểu Cần",
    "THPT Cầu Quan",
    "THPT Hiếu Tử",
    "THPT Tiểu Cần",
    "Phổ thông Dân tộc nội trú THCS và THPT Trà Cú",
    "THPT Đại An",
    "THPT Hàm Giang",
    "THPT Long Hiệp",
    "THPT Tập Sơn",
    "THPT Trần Văn Long",
    "THPT Lưu Văn Liệt",
    "THPT Nguyễn Thông",
    "THCS và THPT Trưng Vương",
    "THPT Vĩnh Long",
    "THPT Bình Minh",
    "THCS và THPT Đông Thành",
    "THPT Hoàng Thái Hiếu",
    "THCS và THPT Mỹ Thuận",
    "THPT Tân Lược",
    "THPT Tân Quới",
    "THPT Hòa Ninh",
    "THPT Phạm Hùng",
    "THCS và THPT Phú Quới",
    "THPT Mang Thít",
    "THCS và THPT Mỹ Phước",
    "THPT Nguyễn Văn Thiệt",
    "Phổ thông Dân tộc nội trú Vĩnh Long",
    "THCS và THPT Long Phú",
    "THPT Phan Văn Hòa",
    "THPT Song Phú",
    "THPT Tam Bình",
    "THPT Trần Đại Nghĩa",
    "THCS và THPT Hoà Bình",
    "THPT Hựu Thành",
    "THPT Lê Thanh Mừng",
    "THPT Trà Ôn",
    "THPT Vĩnh Xuân",
    "THCS và THPT Hiếu Nhơn",
    "THPT Hiếu Phụng",
    "THPT Nguyễn Hiếu Tự",
    "THCS và THPT Phan Văn Đáng",
    "THCS và THPT Thanh Bình",
    "THPT Võ Văn Kiệt",
    "Phổ thông Hermann Gmeiner Bến Tre",
    "TH - THCS - THPT IGC Bến Tre",
  ],
  "Ninh Bình": [
    "THPT Chuyên Lê Hồng Phong",
    "THPT B Nguyễn Khuyến",
    "THPT A Trần Hưng Đạo",
    "THPT B Nguyễn Huệ",
    "THPT Ngô Quyền",
    "Tiểu học, THCS và THPT Nguyễn Công Trứ",
    "THPT Trần Quang Khải",
    "THPT Dân lập Trần Nhật Duật",
    "THPT Trần Văn Lan",
    "THPT Mỹ Lộc",
    "THPT Lương Thế Vinh",
    "THPT Hoàng Văn Thụ",
    "THPT Hùng Vương",
    "THPT Nguyễn Đức Thuận",
    "THPT Nguyễn Bính",
    "THPT Tống Văn Trân",
    "THPT Phạm Văn Nghị",
    "THPT Mỹ Tho",
    "THPT Ý Yên",
    "THPT Đại An",
    "THPT Đỗ Huy Liêu",
    "THPT Lý Nhân Tông",
    "THPT Lý Tự Trọng",
    "THPT Nam Trực",
    "THPT Nguyễn Du",
    "THPT Phan Bội Châu",
    "THPT Quang Trung",
    "THPT Trần Văn Bảo",
    "THPT Trực Ninh",
    "THPT Trực Ninh B",
    "THPT Nguyễn Trãi",
    "THPT Lê Quý Đôn",
    "THPT Đoàn Kết",
    "THPT Nghĩa Hưng A",
    "THPT Nghĩa Hưng B",
    "THPT Nghĩa Hưng C",
    "THPT Nghĩa Minh",
    "THPT Trần Nhân Tông",
    "THPT A Hải Hậu",
    "THPT B Hải Hậu",
    "THPT C Hải Hậu",
    "THPT Thịnh Long",
    "THPT Tô Hiến Thành",
    "THPT An Phúc",
    "THPT Trần Quốc Tuấn",
    "THPT Vũ Văn Hiếu",
    "THPT Xuân Trường",
    "THPT Xuân Trường B",
    "THPT Xuân Trường C",
    "THPT Nguyễn Trường Thúy",
    "THPT Cao Phong",
    "THPT Giao Thủy",
    "THPT Giao Thủy B",
    "THPT Giao Thủy C",
    "THPT Thiên Trường",
    "THPT Quất Lâm",
    "THPT Chuyên Biên Hòa",
    "THPT A Phủ Lý",
    "THPT B Phủ Lý",
    "THPT C Phủ Lý",
    "Trung học cơ sở & THPT Nguyễn Tất Thành - Phân hiệu Hà Nam",
    "THPT Dân lập Lương Thế Vinh",
    "THPT Nam Lý",
    "THPT Nam Cao",
    "THPT Bắc Lý",
    "THPT Lý Nhân",
    "THPT Dân lập Trần Hưng Đạo",
    "THPT A Bình Lục",
    "THPT B Bình Lục",
    "THPT C Bình Lục",
    "THPT A Nguyễn Khuyến",
    "THPT Dân lập Bình Lục",
    "THPT A Duy Tiên",
    "THPT B Duy Tiên",
    "THPT Nguyễn Hữu Tiến",
    "THPT A Kim Bảng",
    "THPT B Kim Bảng",
    "THPT C Kim Bảng",
    "THPT Lý Thường Kiệt",
    "THPT A Thanh Liêm",
    "THPT B Thanh Liêm",
    "THPT C Thanh Liêm",
    "THPT Lê Hoàn",
    "THPT Dân lập Thanh Liêm",
    "THPT Chuyên Lương Văn Tụy",
    "THPT A Nguyễn Huệ",
    "THPT B Trần Hưng Đạo",
    "THPT Đinh Tiên Hoàng",
    "THPT Ninh Bình - Bạc Liêu",
    "THPT Phổ thông Thực hành Sư phạm Tràng An",
    "THPT Hoa Lư A",
    "THPT Gia Viễn A",
    "THPT Gia Viễn B",
    "THPT Gia Viễn C",
    "THPT Nho Quan A",
    "THPT Nho Quan B",
    "THPT Nho Quan C",
    "THPT Dân tộc Nội trú Ninh Bình",
    "THPT Yên Khánh A",
    "THPT Yên Khánh B",
    "THPT Vũ Duy Thanh",
    "THPT Kim Sơn A",
    "THPT Kim Sơn B",
    "THPT Kim Sơn C",
    "THPT Bình Minh",
    "THPT Yên Mô A",
    "THPT Yên Mô B",
    "THPT Trương Hán Siêu",
  ],
  "Thanh Hóa": [
    "THPT Mường Lát",
    "THPT Quan Hóa",
    "THPT Quan Sơn",
    "THCS&THPT Quan Sơn",
    "THPT Bá Thước",
    "THPT Hà Văn Mao",
    "THCS&THPT Bá Thước",
    "THPT Lang Chánh",
    "THPT Như Xuân",
    "THPT Như Xuân 2",
    "THPT Cầm Bá Thước",
    "THPT Thường Xuân 2",
    "THPT Như Thanh",
    "THPT Như Thanh 2",
    "THPT Ngọc Lặc",
    "THPT Lê Lai",
    "THPT Bắc Sơn",
    "THPT Thạch Thành 1",
    "THPT Thạch Thành 2",
    "THPT Thạch Thành 3",
    "THPT Thạch Thành 4",
    "THPT Cẩm Thủy 1",
    "THPT Cẩm Thủy 2",
    "THPT Cẩm Thủy 3",
    "THPT Vĩnh Lộc",
    "THPT Tống Duy Tân",
    "THPT Hà Trung",
    "THPT Hoàng Lê Kha",
    "THPT Yên Định 1",
    "THPT Yên Định 2",
    "THPT Yên Định 3",
    "THCS&THPT Thống Nhất",
    "THCS&THPT Nghi Sơn",
    "THPT Lê Lợi",
    "THPT Lê Hoàn",
    "THPT Lam Kinh",
    "THPT Thọ Xuân 4",
    "THPT Thọ Xuân 5",
    "THPT Lê Văn Hưu",
    "THPT Thiệu Hóa",
    "THPT Nguyễn Quán Nho",
    "THPT Triệu Sơn 1",
    "THPT Triệu Sơn 2",
    "THPT Triệu Sơn 3",
    "THPT Triệu Sơn 4",
    "THPT Triệu Sơn 5",
    "THPT Đông Sơn 1",
    "Phổ thông Nguyễn Mộng Tuân",
    "THPT Đông Sơn 2",
    "THPT Nông Cống 1",
    "THPT Nông Cống 2",
    "THPT Nông Cống 3",
    "THPT Nông Cống 4",
    "THPT Quảng Xương 1",
    "THPT Quảng Xương 2",
    "THPT Chu Văn An",
    "THPT Quảng Xương 4",
    "THPT Đặng Thai Mai",
    "THPT Tĩnh Gia 1",
    "THPT Tĩnh Gia 2",
    "THPT Tĩnh Gia 3",
    "THPT Tĩnh Gia 4",
    "THPT Ba Đình",
    "THPT Mai Anh Tuấn",
    "THPT Nga Sơn",
    "THPT Lương Đắc Bằng",
    "THPT Hoằng Hóa 2",
    "THPT Hoằng Hóa 3",
    "THPT Hoằng Hóa 4",
    "THPT Hậu Lộc 1",
    "THPT Hậu Lộc 2",
    "THPT Hậu Lộc 3",
    "THPT Hậu Lộc 4",
    "THPT Chuyên Lam Sơn",
    "THPT Hàm Rồng",
    "THPT Đào Duy Từ",
    "THPT Tô Hiến Thành",
    "THPT Dân tộc Nội trú tỉnh",
    "THPT Nguyễn Trãi",
    "THPT Bỉm Sơn",
    "THPT Lê Hồng Phong",
    "THPT Sầm Sơn",
    "THPT Nguyễn Thị Lợi",
    "THPT Thường Xuân 3",
    "THCS&THPT Quan Hóa",
    "THCS&THPT Như Thanh",
    "THPT Dân tộc Nội trú Ngọc Lặc",
    "THCS&THPT Như Xuân",
    "Tiểu học, THCS&THPT Hồng Đức",
    "THPT Lý Thường Kiệt",
    "THPT Trường Thi",
    "THPT Đào Duy Anh",
    "Tiểu học, THCS&THPT Đông Bắc Ga",
    "Tiểu học, THCS&THPT Vinschool Star City",
    "Tiểu học, THCS&THPT QTH School",
    "THPT Nguyễn Huệ",
    "Tiểu học, THCS&THPT Nobel School",
    "Tiểu học, THCS&THPT Nobel School II",
    "Tiểu học, THCS&THPT Nobel School III",
    "Tiểu học, THCS&THPT Nobel School Yên Định",
    "Tiểu học, THCS&THPT Nobel School V",
  ],
  "Bắc Ninh": [
    "THPT Chuyên Bắc Ninh",
    "THPT Chuyên Bắc Giang",
    "THPT Hàn Thuyên",
    "THPT Hoàng Quốc Việt",
    "THPT Lý Nhân Tông",
    "THPT Hàm Long",
    "THPT Lý Thường Kiệt số 2",
    "THPT Lý Thái Tổ",
    "THPT Nguyễn Văn Cừ",
    "THPT Ngô Gia Tự",
    "THPT Thuận Thành số 1",
    "THPT Thuận Thành số 2",
    "THPT Thuận Thành số 3",
    "THPT Quế Võ số 1",
    "THPT Quế Võ số 2",
    "THPT Quế Võ số 3",
    "THPT Gia Bình số 1",
    "THPT Lê Văn Thịnh",
    "THPT Lương Tài",
    "THPT Lương Tài số 2",
    "THPT Tiên Du số 1",
    "THPT Nguyễn Đăng Đạo",
    "THPT Yên Phong số 1",
    "THPT Yên Phong số 2",
    "THPT Việt Yên số 1",
    "THPT Việt Yên số 2",
    "THPT Lý Thường Kiệt số 1",
    "THPT Tân Yên số 1",
    "THPT Tân Yên số 2",
    "THPT Nhã Nam",
    "THPT Lục Nam",
    "THPT Phương Sơn",
    "THPT Cẩm Lý",
    "THPT Tứ Sơn",
    "THPT Yên Thế",
    "THPT Bố Hạ",
    "THPT Mỏ Trạng",
    "THPT Hiệp Hòa số 1",
    "THPT Hiệp Hòa số 2",
    "THPT Hiệp Hòa số 3",
    "THPT Hiệp Hòa số 4",
    "THPT Yên Dũng số 1",
    "THPT Yên Dũng số 2",
    "THPT Yên Dũng số 3",
    "THPT Sơn Động số 1",
    "THPT Sơn Động số 2",
    "THPT Sơn Động số 3",
    "THPT Chu Văn An",
    "THPT Lục Ngạn",
    "THPT Phượng Sơn",
    "THPT Lương Thế Vinh",
    "THPT Lạng Giang số 1",
    "THPT Lạng Giang số 2",
    "THPT Lạng Giang số 3",
    "THPT Ngô Sĩ Liên",
    "THPT Thái Thuận",
    "THPT Giáp Hải",
    "Phổ thông Dân tộc nội trú tỉnh Bắc Giang",
    "Dân tộc nội trú THCS và THPT Nguyễn Tất Thành",
    "Phổ thông Dân tộc nội trú Sơn Động",
    "THPT Nguyễn Du",
    "Phổ thông Liên cấp Chu Văn An",
    "Phổ thông Liên cấp Đào Duy Từ",
    "Phổ thông Liên cấp Lương Thế Vinh",
    "TH, THCS & THPT FPT Bắc Ninh",
    "THPT Từ Sơn",
    "Phổ thông liên cấp Lý Công Uẩn",
    "Phổ thông IVS",
    "Phổ thông năng khiếu TDTT Olympic",
    "THPT Kinh Bắc",
    "THPT Thiên Đức",
    "THPT Phố Mới",
    "THPT Trần Hưng Đạo",
    "THPT Gia Bình số 3",
    "THPT Lương Tài số 3",
    "THPT Hải Á",
    "THPT Trần Nhân Tông",
    "THPT Lê Quý Đôn",
    "THPT Nguyễn Trãi",
    "TH, THCS & THPT Maple Leaf Academy",
    "TH, THCS & THPT FPT Bắc Giang",
    "THPT Nguyên Hồng",
    "TH, THCS & THPT Quốc tế Success Academy",
    "THPT Lê Hồng Phong",
    "THPT Thanh Lâm",
    "THPT Đồi Ngô",
    "THPT Hoàng Hoa Thám",
    "THPT Thân Nhân Trung",
    "TH, THCS&THPT Nguyễn Bỉnh Khiêm",
    "THPT Quang Trung",
    "THPT Hiệp Hòa số 5",
    "THPT Hiệp Hòa số 6",
    "Phổ thông Quốc tế Kinh Bắc",
    "Quốc tế Him Lam Bắc Ninh",
  ],
  "Đà Nẵng": [
    "THPT chuyên Lê Quý Đôn",
    "THPT chuyên Nguyễn Bỉnh Khiêm",
    "THPT chuyên Lê Thánh Tông",
    "THPT Phan Châu Trinh",
    "THPT Trần Phú",
    "THPT Nguyễn Hiền",
    "THPT Thanh Khê",
    "THPT Thái Phiên",
    "THPT Hoàng Hoa Thám",
    "THPT Tôn Thất Tùng",
    "THPT Ngô Quyền",
    "THPT Sơn Trà",
    "THPT Hoà Vang",
    "THCS-THPT Nguyễn Khuyến",
    "THPT Cẩm Lệ",
    "THPT Nguyễn Văn Thoại",
    "THPT Liên Chiểu",
    "THPT Nguyễn Trãi",
    "THPT Nguyễn Thượng Hiền",
    "THPT Ngũ Hành Sơn",
    "THPT Võ Chí Công",
    "THPT Phan Thành Tài",
    "THPT Ông Ích Khiêm",
    "THPT Phạm Phú Thứ",
    "THPT Duy Tân",
    "THPT Phan Bội Châu",
    "THPT Trần Cao Vân",
    "THPT Lê Quý Đôn",
    "THPT Trần Quý Cáp",
    "PTDTNT THPT Quảng Nam",
    "THPT Nguyễn Trãi – Hội An",
    "THPT Trần Hưng Đạo",
    "THPT Sào Nam",
    "THPT Lê Hồng Phong",
    "THPT Nguyễn Hiền – Duy Xuyên",
    "THPT Nguyễn Duy Hiệu",
    "THPT Hoàng Diệu",
    "THPT Phạm Phú Thứ – Gò Nổi",
    "THPT Lương Thế Vinh",
    "THPT Nguyễn Khuyến",
    "THPT Huỳnh Ngọc Huệ",
    "THPT Chu Văn An",
    "THPT Đỗ Đăng Tuyển",
    "THPT Lương Thúc Kỳ",
    "THPT Hùng Vương",
    "THPT Quế Sơn",
    "THPT Nguyễn Văn Cừ",
    "THPT Nông Sơn",
    "THPT Trần Đại Nghĩa",
    "THPT Hiệp Đức",
    "THPT Tiểu La",
    "THPT Nguyễn Thái Bình",
    "THPT Thái Phiên – Thăng Bình",
    "THPT Lý Tự Trọng",
    "THPT Núi Thành",
    "THPT Cao Bá Quát",
    "THPT Nguyễn Huệ",
    "THPT Huỳnh Thúc Kháng",
    "THPT Phan Châu Trinh – Tiên Phước",
    "THPT Bắc Trà My",
    "THPT Quang Trung – Đông Giang",
    "THPT Tố Hữu",
    "THPT Khâm Đức",
    "THPT Võ Nguyên Giáp",
    "THPT Trần Văn Dư",
    "THPT Nam Trà My",
    "THPT Tây Giang",
    "THPT Nguyễn Dục",
    "PTDTNT THCS và THPT Nước Oa",
    "THPT Trần Phú – Việt An",
    "THPT Âu Cơ",
    "THPT Nguyễn Văn Trỗi",
    "PTDTNT THCS và THPT Phước Sơn",
    "PTDTNT THCS và THPT Nam Trà My",
    "THCS - THPT Việt Nhật",
    "TH-THCS-THPT Sky-Line",
    "THPT Quang Trung",
    "THPT Hermann Gmeiner",
    "Phổ thông Liên cấp Khai Trí",
    "THCS-THPT Hiển Nhân",
    "TH-THCS-THPT Việt Nhật",
    "TH-THCS-THPT Quốc tế Hoa Kỳ APU",
    "THPT FPT Đà Nẵng",
    "TH-THCS-THPT Anh Quốc",
  ],
  "Hưng Yên": [
    "THPT Chuyên Hưng Yên",
    "THPT Hưng Yên",
    "THPT Mỹ Hào",
    "THPT Nguyễn Thiện Thuật",
    "THPT Văn Giang",
    "THPT Dương Quảng Hàm",
    "THPT Văn Lâm",
    "THPT Trưng Vương",
    "THPT Tiên Lữ",
    "THPT Trần Hưng Đạo",
    "THPT Hoàng Hoa Thám",
    "THPT Phù Cừ",
    "THPT Nam Phù Cừ",
    "THPT Ân Thi",
    "THPT Nguyễn Trung Ngạn",
    "THPT Phạm Ngũ Lão",
    "THPT Kim Động",
    "THPT Đức Hợp",
    "THPT Nghĩa Dân",
    "THPT Khoái Châu",
    "THPT Trần Quang Khải",
    "THPT Nguyễn Siêu",
    "THPT Yên Mỹ",
    "THPT Triệu Quang Phục",
    "THPT Minh Châu",
    "THPT Chuyên Thái Bình",
    "THPT Lê Quý Đôn",
    "THPT Nguyễn Đức Cảnh",
    "THPT Quách Đình Bảo",
    "THPT Nguyễn Trãi",
    "THPT Vũ Tiên",
    "THPT Lý Bôn",
    "THPT Phạm Quang Thẩm",
    "THPT Nguyễn Du",
    "THPT Chu Văn An",
    "THPT Bắc Kiến Xương",
    "THPT Bình Thanh",
    "THPT Tiên Hưng",
    "THPT Bắc Đông Quan",
    "THPT Nam Đông Quan",
    "THPT Mê Linh",
    "THPT Bắc Duyên Hà",
    "THPT Hưng Nhân",
    "THPT Nam Duyên Hà",
    "THPT Đông Hưng Hà",
    "THPT Quỳnh Côi",
    "THPT Phụ Dực",
    "THPT Quỳnh Thọ",
    "THPT Thái Ninh",
    "THPT Đông Thụy Anh",
    "THPT Tây Thụy Anh",
    "THPT Thái Phúc",
    "THPT Tây Tiền Hải",
    "THPT Nam Tiền Hải",
    "THPT Đông Tiền Hải",
    "THPT Tô Hiệu",
    "THPT Quang Trung",
    "THPT Ngô Quyền",
    "THPT Newton Hưng Yên",
    "THPT Đinh Tiên Hoàng",
    "THPT Phùng Hưng",
    "THPT Hồng Bàng",
    "TH, THCS & THPT Hồng Đức",
    "THPT Nguyễn Tất Thành",
    "THPT Hùng Vương",
    "TH, THCS & THPT Everest",
    "THPT Nguyễn Công Hoan",
    "TH, THCS & THPT Vinschool Ocean Park 2",
    "TH, THCS & THPT Edison",
    "TH, THCS & THPT Greenfield",
    "TH, THCS & THPT Marie Curie Thái Bình",
    "TH, THCS & THPT Asahi Thái Bình",
    "THPT Đông Quan",
    "THPT Lạc Long Quân",
    "THPT Hồng Đức",
    "THPT Trần Thị Dung",
    "THPT Nguyễn Huệ",
    "THPT Trần Quốc Tuấn",
    "THPT Diêm Điền",
    "THPT Hoàng Văn Thái",
  ],
  "An Giang": [
    "THPT chuyên Thoại Ngọc Hầu",
    "THPT Long Xuyên",
    "THPT Nguyễn Hiền",
    "THPT Nguyễn Công Trứ",
    "Phổ thông Thực hành Sư phạm",
    "Trung học Cơ sở và THPT Mỹ Hòa Hưng",
    "THPT Chưởng Binh Lễ",
    "Phổ thông iSCHOOL Long Xuyên",
    "Phổ thông Quốc tế GIS",
    "THPT chuyên Thủ Khoa Nghĩa",
    "THPT Châu Thị Tế",
    "THPT Võ Thị Sáu",
    "Phổ thông Dân tộc nội trú THPT An Giang",
    "THPT Tân Châu",
    "THPT Nguyễn Sinh Sắc",
    "THPT Nguyễn Quang Diêu",
    "THPT Vĩnh Xương",
    "THPT Châu Phong",
    "THPT Nguyễn Hữu Cảnh",
    "THPT Châu Văn Liêm",
    "THPT Ung Văn Khiêm",
    "THPT Huỳnh Thị Hưởng",
    "THPT Võ Thành Trinh",
    "THPT Lương Văn Cù",
    "THPT Nguyễn Văn Hưởng",
    "THPT Trần Văn Thành",
    "THPT Thạnh Mỹ Tây",
    "THPT Châu Phú",
    "THPT Bình Mỹ",
    "Trung học Cơ sở và THPT Bình Long",
    "Trung học Cơ sở và THPT Bình Chánh",
    "THPT Chu Văn An",
    "THPT Nguyễn Chí Thanh",
    "THPT Hòa Lạc",
    "THPT Bình Thạnh Đông",
    "Trung học Cơ sở và THPT Phú Tân",
    "THPT An Phú",
    "THPT Quốc Thái",
    "Trung học Cơ sở và THPT Vĩnh Lộc",
    "Trung học Cơ sở và THPT Long Bình",
    "THPT Nguyễn Văn Thoại",
    "THPT Nguyễn Khuyến",
    "THPT Vĩnh Trạch",
    "THPT Vọng Thê",
    "THPT Nguyễn Bỉnh Khiêm",
    "THPT Vĩnh Bình",
    "THPT Cần Đăng",
    "Trung học Cơ sở và THPT Vĩnh Nhuận",
    "THPT Nguyễn Trung Trực 2",
    "THPT Ba Chúc",
    "Trung học Cơ sở và THPT Cô Tô",
    "THPT Tịnh Biên",
    "THPT Chi Lăng",
    "THPT Xuân Tô",
    "THPT Thoại Ngọc Hầu",
    "THPT Nguyền Thần Hiến",
    "THPT Kiên Lương",
    "Trung học Cơ sở và THPT Ba Hòn",
    "THPT Phú Quốc",
    "THPT An Thới",
    "THPT Dương Đông",
    "TH,THCS và THPT Vinschool",
    "Trung học Cơ sở và THPT Bình Sơn",
    "Trung học Cơ sở và THPT Nam Thái Sơn",
    "THPT Hòn Đất",
    "Trung học Cơ sở và THPT Phan Thị Ràng",
    "Trung học Cơ sở và THPT Nguyễn Hùng Hiệp",
    "THPT Sóc Sơn",
    "THPT An Minh",
    "THPT chuyên Huỳnh Mẫn Đạt",
  ],
  "Quảng Ngãi": [
    "THPT chuyên Lê Khiết",
    "THPT chuyên Nguyễn Tất Thành",
    "THPT Bình Sơn",
    "THCS & THPT Vạn Tường",
    "THPT Trần Kỳ Phong",
    "THPT Lê Quý Đôn",
    "THPT Võ Nguyên Giáp",
    "THPT Ba Gia",
    "THPT Sơn Mỹ",
    "THPT Huỳnh Thúc Kháng",
    "THPT Trần Quốc Tuấn",
    "THPT Lê Trung Đình",
    "THPT Số 1 Tư Nghĩa",
    "THPT Số 2 Tư Nghĩa",
    "THPT Thu Xà",
    "THPT Chu Văn An",
    "THPT Số 2 Đức Phổ",
    "THPT Lý Sơn",
    "THPT Ba Tơ",
    "THPT Sơn Hà",
    "THPT Trà Bồng",
    "THCS và THPT Phó Mục Gia",
    "THPT Đinh Tiên Hoàng",
    "THPT Tây Trà",
    "THPT Phạm Kiệt",
    "THCS&THPT Phạm Kiệt",
    "THPT Quang Trung",
    "PTDTNT THPT Tỉnh Quảng Ngãi",
    "PTDTNT THCS và THPT Đăk Rve",
    "PTDTNT THPT Đăk Glei",
    "PTDTNT THPT Đăk Hà",
    "PTDTNT THPT Đăk Tô",
    "PTDTNT THPT Ia Tơi",
    "PTDTNT THPT Kon Tum",
    "PTDTNT THPT Măng Đen",
    "PTDTNT THPT Sa Thầy",
    "PTDTNT THPT Tu Mơ Rông",
    "THCS và THPT Liên Việt Kon Tum",
    "THCS và THPT Ngô Mây",
    "THPT Kon Tum",
    "THPT Nguyễn Huệ",
    "THPT Nguyễn Trãi",
    "THPT Nguyễn Văn Cừ",
    "THPT Phan Chu Trinh",
    "THPT Phan Đình Phùng",
    "THPT Trần Hưng Đạo",
    "THPT Trần Phú",
    "THPT Trường Chinh",
    "THPT Duy Tân",
    "THPT TT Trương Định",
    "THPT TT Hoàng Văn Thụ",
    "THCS và THPT TT Tôn Đức Thắng",
  ],
  "Phú Thọ": [
    "THPT chuyên Hùng Vương",
    "THPT Việt Trì",
    "THPT Công nghiệp Việt Trì",
    "THPT kỹ thuật Việt Trì",
    "Phổ thông Hermann Gmeiner Việt Trì",
    "THPT Hùng Vương",
    "THPT Long Châu Sa",
    "THPT Phong Châu",
    "THPT Phù Ninh",
    "THPT Trung Giáp",
    "THPT Tử Đà",
    "THPT Tam Nông",
    "THPT Mỹ Văn",
    "THPT Hưng Hóa",
    "THPT Tân Sơn",
    "THPT Minh Đài",
    "THPT Thanh Ba",
    "THPT Yển Khê",
    "THPT Thanh Sơn",
    "THPT Hương Cần",
    "THPT Văn Miếu",
    "THPT Thanh Thủy",
    "THPT Trung Nghĩa",
    "THPT Yên Lập",
    "THPT Lương Sơn",
    "THPT Minh Hòa",
    "Phổ thông Dân tộc nội trú THCS & THPT Yên Lập",
    "THPT Cẩm Khê",
    "THPT Hiền Đa",
    "THPT Phương Xá",
    "THPT Đoan Hùng",
    "THPT Chân Mộng",
    "THPT Quế Lâm",
    "THPT Hạ Hòa",
    "THPT Vĩnh Chân",
    "THPT Xuân Áng",
    "THPT Vũ Thê Lang",
    "THPT Nguyễn Tất Thành",
    "THPT chất lượng cao Văn Lang",
    "THPT Trần Phú",
    "THPT thị xã Phú Thọ",
    "THPT Trường Thịnh",
    "THPT Lâm Thao",
    "THPT Nguyễn Huệ",
    "THPT Tản Đà",
    "THPT Sông Thao",
    "THPT Nguyễn Bỉnh Khiêm",
    "Phổ thông dân tộc nội trú tỉnh Phú Thọ",
    "Phổ thông chất lượng cao Hùng Vương",
    "THPT chuyên Vĩnh Phúc",
    "THPT chuyên Hoàng Văn Thụ",
    "Phổ thông Dân tộc nội trú THPT Hòa Bình",
    "THPT Công Nghiệp",
  ],
  "Huế": [
    "THPT chuyên Quốc học – Huế",
    "THPT chuyên Khoa học Huế",
    "THPT Hai Bà Trưng",
    "THPT Nguyễn Huệ",
    "THPT Gia Hội",
    "THPT Bùi Thị Xuân",
    "THPT Nguyễn Trường Tộ",
    "Phổ thông Dân tộc Nội trú thành phố Huế",
    "THPT Đặng Trần Côn",
    "THPT Cao Thắng",
    "THPT Thuận Hoá - Trường ĐHSP Huế",
    "THPT Phan Đăng Lưu",
    "THPT Thuận An",
    "THPT Hương Vinh",
    "THPT Phong Điền",
    "THPT Tam Giang",
    "THPT Nguyễn Đình Chiểu",
    "THPT Trần Văn Kỷ",
    "THPT Hoá Châu",
    "THPT Nguyễn Chí Thanh",
    "THPT Tố Hữu",
    "THPT Đặng Huy Trứ",
    "THPT Bình Điền",
    "THPT Hương Trà",
    "THPT Nguyễn Sinh Cung",
    "THPT Vinh Xuân",
    "THPT Hà Trung",
    "THPT Hương Thuỷ",
    "THPT Phú Bài",
    "THPT An Lương Đông",
    "THPT Vinh Lộc",
    "THPT Phú Lộc",
    "THPT Thừa Lưu",
    "THPT Nam Đông",
    "THPT A Lưới",
    "THCS và THPT Hồng Vân",
    "THCS và THPT Trường Sơn",
    "THPT Tư thục Chi Lăng",
  ],
  "Đồng Nai": [
    "THPT Bù Đăng",
    "THPT Chơn Thành",
    "THPT Chu Văn An",
    "THPT Đa Kia",
    "THPT Đắk Ơ",
    "THPT Đồng Phú",
    "THPT Đồng Xoài",
    "THPT Hùng Vương",
    "THPT Lê Quý Đôn",
    "THPT Lộc Hiệp",
    "THPT Lộc Ninh",
    "THPT Lộc Thái",
    "THPT Ngô Quyền",
    "THPT Nguyễn Du",
    "THPT Nguyễn Huệ",
    "THPT Nguyễn Hữu Cảnh",
    "THPT Nguyễn Khuyến",
    "THPT Phú Riềng",
    "THPT Phước Bình",
    "THPT Thanh Hòa",
    "THPT Thị xã Bình Long",
    "THPT Thị xã Phước Long",
    "THPT Thống Nhất",
    "THPT Trần Phú",
    "THPT Chuyên Bình Long",
    "THPT Chuyên Quang Trung",
    "Trung học Cơ sở và THPT Đắk Mai",
    "Trung học Cơ sở và THPT Đăng Hà",
    "Trung học Cơ sở và THPT Đồng Tiến",
    "Trung học Cơ sở và THPT Lương Thế Vinh",
    "Trung học Cơ sở và THPT Minh Hưng",
    "Trung học Cơ sở và THPT Nguyễn Bỉnh Khiêm",
    "Trung học Cơ sở và THPT Tân Tiến",
    "Trung học Cơ sở và THPT Võ Thị Sáu",
    "Phổ thông Dân tộc Nội trú THPT Bình Phước",
    "Phổ thông Dân tộc Nội trú Trung học Cơ sở và THPT Bù Gia Mập",
    "Phổ thông Dân tộc nội trú Trung học Cơ sở và THPT Điểu Ong",
    "THPT chuyên Lương Thế Vinh",
  ],
  "Khánh Hòa": [
    "THPT Lý Tự Trọng",
    "THPT Nguyễn Văn Trỗi",
    "THPT chuyên Lê Quý Đôn",
    "THPT Hà Huy Tập",
    "THPT Hoàng Văn Thụ",
    "Tiểu học, THCS và THPT iSCHOOL Nha Trang",
    "THPT Dân lập Nguyễn Thiện Thuật",
    "THPT Dân lập Lê Thánh Tôn",
    "Phổ thông Hermann Gmeiner Nha Trang",
    "Phổ thông Dân tộc Nội trú tỉnh Khánh Hòa",
    "THPT Huỳnh Thúc Kháng",
    "THPT Tô Văn Ơn",
    "THPT Nguyễn Thị Minh Khai",
    "THPT Lê Hồng Phong",
    "THPT Nguyễn Trãi",
    "THPT Trần Quý Cáp",
    "THPT Trần Cao Vân",
    "THPT Nguyễn Chí Thanh",
    "THPT Tôn Đức Thắng",
    "THPT Hoàng Hoa Thám",
    "THPT Nguyễn Thái Học",
    "THPT Lạc Long Quân",
    "THPT Trần Hưng Đạo",
    "THPT Phan Bội Châu",
    "THPT Ngô Gia Tự",
    "THPT Thăng Long",
    "THPT Khánh Sơn",
    "THPT Nguyễn Huệ",
    "THPT Trần Bình Trọng",
    "THPT Đoàn Thị Điểm",
    "THPT chuyên Lê Quý Đôn – Nam Nha Trang",
    "THPT chuyên Lê Quý Đôn – Đông Hải",
  ],
  "Tây Ninh": [
    "THPT chuyên Hoàng Lê Kha",
    "THPT Lý Thường Kiệt",
    "THPT Tây Ninh",
    "THPT Lê Quý Đôn",
    "THPT Trần Đại Nghĩa",
    "THPT Nguyễn An Ninh",
    "THPT Trần Phú",
    "THPT Lương Thế Vinh",
    "THPT Lê Duẩn",
    "THPT Tân Châu",
    "THPT Tân Hưng",
    "THPT Tân Đông",
    "THPT Nguyễn Thái Bình",
    "THPT Nguyễn Đình Chiểu",
    "THPT Dương Minh Châu",
    "THPT Lê Hồng Phong",
    "THPT Châu Thành",
    "THPT Hoàng Văn Thụ",
    "THPT Nguyễn Trung Trực",
    "THPT Nguyễn Chí Thanh",
    "Phổ thông Dân tộc Nội trú tỉnh Tây Ninh",
    "THPT Huỳnh Thúc Kháng",
    "THPT Nguyễn Huệ",
    "THPT Ngô Gia Tự",
    "THPT Quang Trung",
    "THPT Nguyễn Văn Trỗi",
    "THPT Trần Quốc Đại",
    "THPT Lộc Hưng",
    "THPT Bình Thạnh",
    "THPT Trảng Bàng",
    "THPT Nguyễn Trãi",
    "THPT chuyên Trần Văn Giàu",
  ],
  "Cà Mau": [
    "THPT Bạc Liêu",
    "THPT Lê Thị Riêng",
    "THPT Lê Văn Đẩu",
    "THPT Giá Rai",
    "THPT Võ Văn Kiệt",
    "THPT Ngan Dừa",
    "THPT Phan Ngọc Hiển",
    "THPT chuyên Bạc Liêu",
    "THPT Dân tộc Nội trú tỉnh Bạc Liêu",
    "THPT Trần Văn Bảy",
    "THPT Nguyễn Trung Trực",
    "THPT Điền Hải",
    "THPT Vĩnh Hưng",
    "THPT Gành Hào",
    "THPT Định Thành",
    "THPT Ninh Quới",
    "THPT Ninh Thạnh Lợi",
    "THCS và THPT Trần Văn Lắm",
    "THPT Tân Phong",
    "THPT chuyên Phan Ngọc Hiển",
  ],
  "Hải Phòng": [
    "THPT chuyên Trần Phú",
    "THPT chuyên Nguyễn Trãi",
    "THPT Ngô Quyền",
    "THPT Kiến An",
    "THPT Quang Trung",
    "THPT Trần Hưng Đạo",
    "THPT Thanh Hà",
  ],
  "Gia Lai": [
    "THPT chuyên Hùng Vương",
    "THPT chuyên Lê Quý Đôn",
    "THPT chuyên Chu Văn An",
    "THPT Quốc học Quy Nhơn",
  ],
  "Cần Thơ": [
    "THPT chuyên Lý Tự Trọng",
    "THPT chuyên Vị Thanh",
    "THPT chuyên Nguyễn Thị Minh Khai",
    "THPT Châu Văn Liêm",
    "THPT Phan Thanh Giản",
  ],
  "Đồng Tháp": [
    "THPT chuyên Nguyễn Quang Diêu",
    "THPT chuyên Nguyễn Đình Chiểu",
    "THPT chuyên Tiền Giang",
    "THPT Lấp Vò 2",
    "THPT thành phố Sa Đéc",
  ],
  "Lâm Đồng": [
    "THPT chuyên Thăng Long",
    "THPT chuyên Bảo Lộc",
    "THPT chuyên Trần Hưng Đạo",
    "THPT chuyên Nguyễn Chí Thanh",
    "Phổ thông Dân tộc Nội trú Lâm Đồng",
    "THPT Bùi Thị Xuân",
  ],
  "Nghệ An": [
    "THPT chuyên Phan Bội Châu",
    "THPT Đô Lương 1",
    "THPT Huỳnh Thúc Kháng",
    "THPT Lê Viết Thuật",
    "THPT chuyên Đại học Vinh",
  ],
  "Thái Nguyên": [
    "THPT chuyên Thái Nguyên",
    "THPT chuyên Bắc Kạn",
    "THPT Chu Văn An",
    "THPT Lương Ngọc Quyến",
  ],
  "Lào Cai": [
    "THPT chuyên Lào Cai",
    "THPT chuyên Nguyễn Tất Thành",
    "THPT Nguyễn Huệ",
  ],
  "Quảng Trị": [
    "THPT chuyên Lê Quý Đôn",
    "THPT chuyên Võ Nguyên Giáp",
    "THPT Quảng Trị",
  ],
  "Sơn La": [
    "THPT chuyên Sơn La",
    "THPT Mộc Lỵ",
  ],
  "Đắk Lắk": [
    "THPT chuyên Nguyễn Du",
    "THPT chuyên Lương Văn Chánh",
  ],
  "Tuyên Quang": [
    "THPT chuyên Tuyên Quang",
    "THPT chuyên Hà Giang",
  ],
  "Quảng Ninh": [
    "THPT Cẩm Phả",
    "THPT chuyên Hạ Long",
  ],
  "Cao Bằng": [
    "THPT thành phố Cao Bằng",
    "THPT chuyên Cao Bằng",
  ],
  "Lạng Sơn": [
    "THPT chuyên Chu Văn An",
  ],
  "Hà Tĩnh": [
    "THPT chuyên Hà Tĩnh",
  ],
  "Điện Biên": [
    "THPT chuyên Lê Quý Đôn",
  ],
  "Lai Châu": [
    "THPT chuyên Lê Quý Đôn",
  ],
};

export const TRUONG_HOC_OPTIONS: string[] = [
  ...TRUONG_DAI_HOC_Y_DUOC_CONG_LAP,
  ...TRUONG_DAI_HOC_Y_DUOC_TU_THUC,
  ...Object.entries(THPT_THEO_TINH).flatMap(([tinh, ds]) => ds.map((ten) => `${ten} – ${tinh}`)),
];
